services:
    entity_manager:
        class: !require '@DatabaseBundle://Database/EntityManager'
        arguments:
            - '@container'
            - '@config'

    entity:
        class: !require '@DatabaseBundle://Annotation/Entity'
        tags: ['annotation']
